const poemData = [
    { text: "鲁", py: "lǔ", zh: "鲁国。", en: "The State of Lu." },
    { text: "有", py: "yǒu", zh: "有一个。", en: "There was a person who" },
    { text: "执", py: "zhí", zh: "动词，拿着，握着。", en: "held", exam: true },
    { text: "长竿", py: "cháng gān", zh: "长竹竿。", en: "a long bamboo pole" },
    { text: "入", py: "rù", zh: "进入。", en: "and tried to enter" },
    { text: "城门", py: "chéng mén", zh: "城门。", en: "the city gate." },
    { text: "者", py: "zhě", zh: "……的人。", en: "The man" },
    { text: "，", punc: true },
    { text: "初", py: "chū", zh: "副词，起初，刚开始。", en: "at first", exam: true },
    { text: "竖", py: "shù", zh: "竖着，垂直地。", en: "vertically" },
    { text: "执", py: "zhí", zh: "拿着。", en: "held" },
    { text: "之", py: "zhī", zh: "代词，代指长竿。", en: "it," },
    { text: "，", punc: true },
    { text: "不可", py: "bù kě", zh: "不能，无法。", en: "but could not" },
    { text: "入", py: "rù", zh: "进去。", en: "enter;" },
    { text: "；", punc: true },
    { text: "横", py: "héng", zh: "横着，水平地。", en: "then horizontally" },
    { text: "执", py: "zhí", zh: "拿着。", en: "held" },
    { text: "之", py: "zhī", zh: "它。", en: "it," },
    { text: "，", punc: true },
    { text: "亦", py: "yì", zh: "也。", en: "but also" },
    { text: "不可", py: "bù kě", zh: "不能。", en: "could not" },
    { text: "入", py: "rù", zh: "进去。", en: "enter." },
    { text: "。", punc: true },
    { text: "计无所出", py: "jì wú suǒ chū", zh: "想不出任何办法。“计”，办法；“出”，产生。", en: "He was completely at his wits' end.", exam: true },
    { text: "。", punc: true },
    { text: "俄", py: "é", zh: "副词，一会儿，不久（文言常考时间副词）。", en: "Soon / after a short while,", exam: true },
    { text: "有", py: "yǒu", zh: "有一个。", en: "an" },
    { text: "老父", py: "lǎo fǔ", zh: "古代对老年男子的尊称，老人（“父”读作 fǔ）。", en: "old man", exam: true },
    { text: "至", py: "zhì", zh: "来到。", en: "arrived" },
    { text: "，", punc: true },
    { text: "曰", py: "yuē", zh: "说。", en: "and said:" },
    { text: "：“", punc: true },
    { text: "吾", py: "wú", zh: "我。", en: "“I" },
    { text: "非", py: "fēi", zh: "不是。", en: "am not" },
    { text: "圣人", py: "shèng rén", zh: "智慧最高超、无所不知的圣人。", en: "a sage," },
    { text: "，", punc: true },
    { text: "但", py: "dàn", zh: "副词，只，仅仅。", en: "but" },
    { text: "见事", py: "jiàn shì", zh: "经历的事情，见过的事物。", en: "I have seen many" },
    { text: "多", py: "duō", zh: "多。", en: "things" },
    { text: "矣", py: "yǐ", zh: "了（表陈述语气）。", en: "in my life!" },
    { text: "！", punc: true },
    { text: "何不", py: "hé bù", zh: "为什么不……呢（表提议的反问词）。", en: "Why don't you" },
    { text: "以", py: "yǐ", zh: "介词，用，拿。", en: "use" },
    { text: "锯", py: "jù", zh: "锯子。", en: "a saw" },
    { text: "中", py: "zhōng", zh: "从中间，正中。", en: "to cut it from the middle" },
    { text: "截", py: "jié", zh: "动词，截断，砍断。", en: "and then", exam: true },
    { text: "而", py: "aim", zh: "连词，表顺承，然后。", en: "go" },
    { text: "入", py: "rù", zh: "进去？法”", en: "in?”" },
    { text: "?”", punc: true },
    { text: "遂", py: "suì", zh: "副词，于是，就。", en: "So he then", exam: true },
    { text: "依", py: "yī", zh: "依照，听从。", en: "followed the advice" },
    { text: "而", py: "ér", zh: "连词，表顺承。", en: "and" },
    { text: "截", py: "jié", zh: "截断。", en: "sawed" },
    { text: "之", py: "zhī", zh: "它（指长竿）。", en: "it." },
    { text: "。", punc: true }
];
